### PR TITLE
Remove all references to the old repo/name LaunchMyApp

### PR DESCRIPTION
**Pull request by pke**

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Thanks man!

**Comment by pke** [comment]
And should `window.plugins.launchmyapp` really be on `window`. The social plugin also does this but I believe the common pattern is to put them under `window.cordova.plugins`.

**Comment by EddyVerbruggen** [comment]
It is what it is

**Comment by pke** [comment]
My question was more like shouldn't we normalise that and slowly deprecate `window.plugins.*` in a separate PR?

**Comment by EddyVerbruggen** [comment]
I appreciate the suggestion but no thanks. It's never been an issue and I'm not going to change the namespace of tens of plugins.

**Comment by pke** [comment]
just for info, which tens of plugins would that be?

**Comment by EddyVerbruggen** [comment]
The ones I created and maintain.

Just for my info, are you stalking me?

**Comment by pke** [comment]
> Just for my info, are you stalking me?

no, I try to make sense of the grown cordova ecosystem. It sometimes feels not really production ready with all the quirks and inconsistencies that pop up.

**Comment by EddyVerbruggen** [comment]
Most of those plugins are created by authors in their spare time suiting mostly their own usecase so that's a fair assessment.

**Pull request merged**
