### PR TITLE
Add wp8 support

### PR DESCRIPTION
**Pull request by nadyaA**
Cordova plugin that enables auto-launching apps using URI associations for Windows Phone 8.
It uses a hook to register a CompositeUriMapper that is used to handle native code URI mapping, if needed.

### CODE REVIEW

**Comment by nadyaA** [comment]
ping @EddyVerbruggen

**Comment by EddyVerbruggen** [comment]
You. Are. Awesome. Thanks!

**Comment by nadyaA** [comment]
Happy to contribute :smiley_cat:

**Comment by cmgustavo** [comment]
I have an error when adding this plugin for WP8:

```
Fetching plugin "https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git" via git clone
Repository "https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git" checked out to git ref "master".
Installing "cordova-plugin-customurlscheme" for wp8
TypeError: Cannot call method 'replace' of undefined
    at C:\cygwin64\home\bitpay\copay\cordova\project\plugins\cordova-plugin-customurlscheme\src\wp8\hooks\add-uri-mapper.js:13:21
    at C:\Users\bitpay\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16
    at fs.js:208:20
    at C:\Users\bitpay\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:230:16
    at Object.oncomplete (fs.js:108:15)
* ERROR. Exiting...
```

I have `Cordova v5.3.3`. I 'll appreciate your help to solve this issue. 

Thanks!

**Comment by cmgustavo** [comment]
Using the latest release on NPM, it works. So, I think there a problem in the master version.

Thanks.

**Comment by EddyVerbruggen** [comment]
@cmgustavo The [latest version on npm](https://www.npmjs.com/package/cordova-plugin-customurlscheme) builds your app but the URL scheme doesn't work, right? As 4.0.0 is on npm which doesn't have this PR merged.

**Comment by EddyVerbruggen** [comment]
Hey @cmgustavo please try 4.1.1, I fixed a compatibility issue with the Cordova CLI (or at least the version I'm using).

**Comment by cmgustavo** [comment]
Yes, it builds the app but URL scheme doesn't work.

I tried with the latest version on npm (4.1.1). It builds Ok, but the app doesn't start. I get: 

```
deviceready has not fired after 5 seconds.
Channel not fired: onCordovaReady
The thread 0xf88 has exited with code 259 (0x103).
```

Note that the app started correctly before the update. I didn't change anything, just updated the plugin.

**Comment by EddyVerbruggen** [comment]
I was planning on testing it on a device tomorrow and will likely run into the same issue. Plz use an older version from npm in the meanwhile. Launching from a URL scheme won't work, but at least your app will.

**Comment by EddyVerbruggen** [comment]
@cmgustavo I reproduced your problem and worked most of my sunday to fix them - please test 4.1.2!

**Comment by cmgustavo** [comment]
Thank you! The App now starts, but the URL handler still not working on my Lumia 630. 

Let me know what do you need to understand better the problem. This used to work (but I don't remember exactly version)

**Comment by EddyVerbruggen** [comment]
Hey @cmgustavo, a few things:

1) What exact WP version are you running?

2) So with a previous version of the plugin you were able to launch the app AND received the actual URL in a `handleOpenUrl` function?

3) Can you try this for me (create a new project and test the plugin)?
```
cordova create customurlschemetest
cd customurlschemetest
cordova platform add wp8
cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME=mycoolapp
cordova prepare wp8
```

Now add this to the `<head>` of your `index.html`:
```js
function handleOpenURL(url) {
  setTimeout(function() {
    alert("received url: " + url);
  }, 500);
}
```

When you deploy that to your phone, run it to see that you have the Cordova starter app. Then [go to this testpage](http://www.x-services.nl/launchmyapp.php) and tap one of the `mycoolapp://` links.

**Pull request merged**
