### PR TITLE
Android style deep linking

### PR DESCRIPTION
**Pull request by eneskaya**
To be able to open the app via  android-app://<app-package-id>/http/host/path additionaly to urlscheme:// there need to be some additional variables added to the AndroidManifest.xml

I've added those as additional variables.

### CODE REVIEW

**Comment by eneskaya** [comment]
Also, see here https://developer.android.com/training/app-indexing/deep-linking.html

**Comment by EddyVerbruggen** [comment]
I think this PR makes those variables mandatory. Let me see if I can make them optional instead.

**Comment by EddyVerbruggen** [comment]
Hey @eneskaya thanks for the PR, it was a step in the right direction!

I had to extract the two `<data>` tags into two separate `<intent-filter>`s, otherwise they would overwrite each other. Now you can use them both in your app.

Also, the `<preference>` tags are now optional so anyone already using this plugin is not bothered with adding three more variables even when they don't need them.

Please test the version currently available in the master branch, I will publish it to npm once I'm sure there's no regression.

Cheers,
Eddy

**Comment by eneskaya** [comment]
Hi,

That's exactly what I found out today too! Thanks :) will have a look

**Comment by slorber** [comment]
Hi,

The code provided in this PR is a problem for my app because it overrides intent-filter declared by another plugin. 

https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/244

**Comment by slorber** [comment]
@eneskaya is it possible with current implementation to support many different paths?

for example /link + /chat, but not /

Wouldn't it be better and more flexible to use `android:pathPattern` instead of `android:pathPrefix` ?

**Comment by eneskaya** [comment]
@slorber I think this really depends on your use case, but yes, I didn't know `android:pathPattern` existed to be honest 😁  Also, I don't use cordova anymore. But I think others would be happy if you extend this plugins capabilities with a PR 👍

**Pull request merged**
